### ISSUE TITLE
Output the correct plots in bbr_experiment.py

### ISSUE THREAD

**Issue by lukehsiao** [jervisfm/GoogleBBR-Replicating-Fig8#2]

**Comment by jervisfm** [comment]
Example data to plot from a test run.

CUBIC:
[VERBOSE] {'loss': [' 1e-05', ' 0.0001', ' 0.001', ' 0.01', ' 0.02', ' 0.05', ' 0.1', ' 0.15', ' 0.2', ' 0.25', ' 0.3', ' 0.4', ' 0.5'], 'goodput': [' 91.1336468319', ' 54.9398962583', ' 9.19779961809', ' 1.84676631496', ' 1.16270432834', ' 0.589580487833', ' 0.368391345223', ' 0.269027516499', ' 0.187257732813', ' 0.170963150682', ' 0.155575185502', ' 0.0437630243981', ' 0.0828415994526']}

BBR:
[VERBOSE] {'loss': [' 1e-05', ' 0.0001', ' 0.001', ' 0.01', ' 0.02', ' 0.05', ' 0.1', ' 0.15', ' 0.2', ' 0.25', ' 0.3', ' 0.4', ' 0.5'], 'goodput': [' 78.2948946196', ' 77.0303332223', ' 68.2795456217', ' 55.9028157865', ' 51.7060955041', ' 45.7544162147', ' 33.9340110396', ' 32.1339630837', ' 28.2579645484', ' 13.4971662497', ' 15.6103622746', ' 14.4164613756', ' 2.06728992209']}

**Comment by jervisfm** [comment]
This is now resolved. See: https://github.com/jervisfm/GoogleBBR-Replicating-Fig8/commit/e3ab5e79734d61afeaf94dfe7aa6b81c0cb70a25
