### ISSUE TITLE
Mahimahi shell dying.

### ISSUE THREAD

**Issue by jervisfm** [jervisfm/GoogleBBR-Replicating-Fig8#4]
When running bbr_experiment.py, sometime I see Mahimahi dying. Check if this error is important or it can be ignored. 

[INFO] Running experiment [loss = 0.25, cong_ctrl = bbr]
Traceback (most recent call last):
  File "client.py", line 82, in <module>
    _run_client()
  File "client.py", line 77, in _run_client
    s.send(msg)
socket.error: [Errno 32] Broken pipe
Died on std::runtime_error: `stdbuf -o0 python client.py 5050 bbr': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1
Died on std::runtime_error: `mm-link 100Mbps.up 100Mbps.down --uplink-log=/tmp/bbr_log --meter-uplink --once -- stdbuf -o0 python client.py 5050 bbr': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1
Died on std::runtime_error: `mm-loss uplink 0.25 mm-link 100Mbps.up 100Mbps.down --uplink-log=/tmp/bbr_log --meter-uplink --once -- stdbuf -o0 python client.py 5050 bbr': process exited with failure status 1
Died on std::runtime_error: `packetshell': process exited with failure status 1

**Comment by lukehsiao** [comment]
Important. This shouldn't happen.

**Comment by jervisfm** [comment]
I will add a note that this was only happening when doing data collection for BBR.

**Comment by lukehsiao** [comment]
I haven't seen this, and you haven't seen this again. I'm going to consider this resolved.
