### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by lukehsiao** [jervisfm/GoogleBBR-Replicating-Fig8#8]
Current title is super long. I propose we name it

`jervisfm/rebbr` or something like `jervisfm/bbr-mahimahi` or `jervisfm/bbr-lossy-eval`

or something else simple/shorter/

**Comment by jervisfm** [comment]
Ack. I will rename it - short relevant names are good all else being equal.

**Comment by jervisfm** [comment]
Renamed it to rebbr.
